from sqlalchemy import Column, Integer, String, DateTime, Text, Float, Date, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from app.database import Base


class Campaign(Base):
    __tablename__ = "campaigns"

    id = Column(Integer, primary_key=True, autoincrement=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False)
    name = Column(String(200), nullable=False)
    campaign_type = Column(String(50))  # social | email | content | ads | integrated
    status = Column(String(20), default="draft")  # draft | planning | active | paused | completed
    start_date = Column(Date)
    end_date = Column(Date)
    budget = Column(Float)
    target_channels = Column(Text)  # JSON array: ["instagram","linkedin","email"]
    strategy_brief = Column(Text)  # JSON: generated by Strategy Agent
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    project = relationship("Project", back_populates="campaigns")
    contents = relationship("Content", back_populates="campaign", cascade="all, delete-orphan")
    tasks = relationship("Task", back_populates="campaign", cascade="all, delete-orphan")
